# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Check index.Rmd
        run: if [ -e index.Rmd ] ; then exit 0 ; else { echo missing index.Rmd ; exit 1 ; } ; fi
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render index.html
        run: if [ -e Makefile ] ; then { echo running Makefile ; make ; } else Rscript -e 'rmarkdown::render("index.Rmd")' ; fi
      - name: Check index.html
        run: if [ -e index.html ] ; then exit 0 ; else { echo missing index.html ; exit 1 ; } ; fi
      - name: Commit results to GitHub repo
        run: |
          git config --local user.email "actions@githu.com"
          git config --local user.name "GitHub Actions"
          git add . || echo "No changes to stage."
          git commit -m 'Re-build index.html' || echo "No changes to commit."
          if [ -e .push ] ; then { git push || echo "No changes to push." ; exit 0 ; } else { echo "No pushing of index.html b/c no .push file in the repo." ; exit 0 ; } ; fi
